### ISSUE TITLE
Contributing guide

### ISSUE THREAD

**Issue by selimfirat** [desResLab/LINFA#10]
Hello, I am reviewing the paper of this repository.

Please provide clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

For 2) and 3), I believe adding short sentences wiith directives to the readme would be enough, and for 1), please check https://mozillascience.github.io/working-open-workshop/contributing/ .

**Comment by daneschi** [comment]
Thank you for the comment.
I have added a contributing guide to the project.
