### ISSUE TITLE
comparison with other software packages

### ISSUE THREAD

**Issue by selimfirat** [desResLab/LINFA#11]
Are there any other commonly-used packages? Either way, please clearly state them in the paper (and in the readme if you wish).

**Comment by robmoss** [comment]
Hi, I'm the other JOSS reviewer. I was going to file a similar issue, but I'll put my comments here. I did a quick search for Python packages that implement some form of variational inference and found the following:

- [PyMc](https://www.pymc.io/projects/examples/en/latest/variational_inference/variational_api_quickstart.html)
- [BayesPy](https://bayespy.org/) (with an accompanying paper, [BayesPy: Variational Bayesian Inference in Python](https://jmlr.csail.mit.edu/papers/volume17/luttinen16a/luttinen16a.pdf))
- [Pyro](https://docs.pyro.ai/en/stable/inference.html) (with [some examples](http://pyro.ai/examples/svi_part_i.html))
- [PyVBMC](https://acerbilab.github.io/pyvbmc/) has  an accompanying [JOSS article](https://doi.org/10.21105/joss.05428) that includes a "Related work" section, which might be a useful reference? 

I also found [this notebook](https://predictivesciencelab.github.io/data-analytics-se/lecture28/hands-on-28.html). which implements VI from scratch in `pytorch`.

Perhaps in the "Capabilities" section, you could add a few remarks to demonstrate how these features of LINFA are more convenient, flexible, powerful, etc, than those found in other packages?

**Comment by robmoss** [comment]
And my apologies if I've misunderstood, but am I right in thinking that the primary distinguishing feature of LINFA is the adaptive training of a surrogate model?

**Comment by daneschi** [comment]
Thank you!
Yes, currently the main differences with the other codes are:
1 - an adaptive discrepancy.
2 - an adaptive annealing algorithm.
Thank you for all your comments. I'm at a conference this week, I'll start
pushing changes related to your comments on Monday.

**Comment by daneschi** [comment]
I have added a new paragraph to the paper highlighting the main feature distinguishing LINFA from the packages you guys pointed out. Thanks!
