### ISSUE TITLE
Plotting outputs with linfa.plot_res

### ISSUE THREAD

**Issue by robmoss** [desResLab/LINFA#14]
After running some examples (#13) I also have a few questions and comments about plotting the results:

- The `linfa.plot_res` module is mentioned in `README.md`, but not anywhere in the online documentation (unless I've missed it). I think it's plausible that a user might look at the online documentation, but not the GitHub repository, so perhaps this module could be included in the online documentation? 
- I discovered that the folder name must end with a trailing slash, otherwise it raises an error:

    ```sh
    python -m linfa.plot_res -n trivial -i 25000 -f results
    Log file not found: resultstrivial/log.txt
    ```

    Line 162 of [`plot_res.py`](https://github.com/desResLab/LINFA/blob/master/linfa/plot_res.py#L162)  concatenates the folder and experiment names. Please consider using [`os.path.join()`](https://docs.python.org/3/library/os.path.html#os.path.join) or [`pathlib.Path`](https://docs.python.org/3/library/pathlib.html) to construct file names.

**Comment by daneschi** [comment]
Thank you for the comments!
- I have added the "plot_res" module to the online documentation under "post-processing and plotting".
- The "plot_res.py" file was edited to use os.path.join().
