### ISSUE TITLE
CI test coverage ? 

### ISSUE THREAD

**Issue by lrnv** [desResLab/LINFA#16]
I am not a specialist of python packages, but would it possible to have your CI (github actions) test for coverage of the package code ? E.g. using a service surch as Codecov ? 

It would allow you to track the coverage and see if some part of your code are more fragile than others, see if you introduce untested code in a new PR, etc..

**Comment by daneschi** [comment]
Thank you @lrnv! I have added coverage to the requirements, linked it to the tests, and added a Codecov macro. The link to the coverage report is now available on README.
